website/apps/ranking/urls.py
from django.urls import path

from .views import GuildRankingView, PlayerRankingView, RankingView, NolifesRankingView


urlpatterns = [
    path('guild-ranking/', GuildRankingView.as_view(), name='guild-ranking-list'),
    path('player-ranking/', PlayerRankingView.as_view(), name='player-ranking-list'),
    path('nolife-ranking/', NolifesRankingView.as_view(), name='nolife-ranking-list'),
    path('ranking/', RankingView.as_view(), name='ranking'),
]

website/apps/users/urls.py
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView, LogoutView
)

from django.urls import path

from .views import (activate, BanListView, CustomLoginView, HomeView,
    CustomPasswordChangeView, CustomPasswordResetView, RegisterView)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('bans/', BanListView.as_view(), name='ban_list'),
    path('activate-email/<str:uidb64>/<str:token>/', activate, name='activate'),

    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(
        'password-reset/confirm/<str:uidb64>/<str:token>/',
        PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
]

website/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('website.apps.users.urls')),
    path('', include('website.apps.ranking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/apps/news/models.py
from django.db import models


class News(models.Model):
    class Meta:
        db_table = 'site_news'
        verbose_name_plural = 'news'
        ordering = ('-date',)

    topic = models.CharField(max_length=30)
    content = models.TextField()

    date = models.DateTimeField()
    author = models.CharField(max_length=12)

website/apps/users/models.py
from datetime import datetime
import re

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.core.validators import RegexValidator
from django.db import connection, models

OK_STATUS = 'OK'
WEBBLK_STATUS = 'WEBBLK'
BLOCK_STATUS = 'BLOCK'

STATUS_CHOICES = [
    (OK_STATUS, 'Konto aktywne'),
    (WEBBLK_STATUS, 'Brak aktywacji email'),
    (BLOCK_STATUS, 'Zbanowane'),
]


class UserManager(BaseUserManager):
    def create_user(self, login, email, social_id, password=None, status=WEBBLK_STATUS):
        if not email:
            raise ValueError('Users must have an email address')

        if not login:
            raise ValueError('Username is required')

        user = self.model(
            email=self.normalize_email(email),
            login=login,
            social_id=social_id,
            status=status
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, email, social_id, password):
        user = self.create_user(
            login,
            email,
            social_id=social_id,
            password=password,
            status=OK_STATUS
        )

        user.admin = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser):
    login = models.CharField('Login / username', max_length=30, unique=True)
    password = models.CharField('Password', max_length=45)
    email = models.EmailField('E-mail', max_length=64, unique=True)
    social_id = models.CharField('Kod usunięcia postaci', max_length=7,
        validators=[RegexValidator(
            regex=r'^\d{7}$',
            message='Kod usunięcia postaci musi zawierać 7 cyfr',
        )]
    )

    powod = models.TextField('Powód banu', null=True, blank=True)
    availDt = models.DateTimeField('Długość banu', default=datetime(1, 1, 1))

    coins = models.IntegerField('SM', default=0)

    admin = models.BooleanField('Admin?', default=False)

    status = models.CharField('Status', max_length=8, choices=STATUS_CHOICES,
        default=WEBBLK_STATUS)

    USERNAME_FIELD = 'login'
    REQUIRED_FIELDS = ['email', 'password', 'social_id']

    objects = UserManager()

    class Meta:
        db_table = "account"

    def get_full_name(self):
        return self.login

    def get_short_name(self):
        return self.login

    def __str__(self):
        return self.login

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def set_password(self, raw_password):
        self.password = self._get_password(raw_password)
        self._password = raw_password

    def _get_password(self, raw_password):
        with connection.cursor() as cursor:
            cursor.execute("SELECT PASSWORD(%s)", [raw_password])
            row = cursor.fetchone()
            return row[0]

    def check_password(self, raw_password):
        password = self._get_password(raw_password)
        return self.password == password

    @property
    def is_staff(self):
        return self.admin

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.status == OK_STATUS

website/apps/users/forms.py
import unicodedata

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm

from .models import User, OK_STATUS


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'login', 'social_id')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)

        if qs.exists():
            raise forms.ValidationError("Podany email już jest użyty.")

        return email

    def clean_login(self):
        login = self.cleaned_data.get('login')
        qs = User.objects.filter(login=login)

        if qs.exists():
            raise forms.ValidationError("Podany login jest już zajęty")

        return login

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if password and password2 and password != password2:
            raise forms.ValidationError("Hasła się nie zgadzają")

        if len(password2) < 4:
            raise forms.ValidationError("Hasło musi mieć co najmniej 4 znaków")

        return password2        


class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'login', 'social_id')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)

        if qs.exists():
            raise forms.ValidationError("Podany email już jest użyty.")

        return email

    def clean_login(self):
        login = self.cleaned_data.get('login')
        qs = User.objects.filter(login=login)

        if qs.exists():
            raise forms.ValidationError("Podany login jest już zajęty")

        return login

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Hasła się nie zgadzają")

        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()

        return user


class UserAdminChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'login', 'social_id')


def _unicode_ci_compare(s1, s2):
    return unicodedata.normalize('NFKC', s1).casefold() == unicodedata.normalize('NFKC', s2).casefold()


class CustomPasswordResetForm(PasswordResetForm):
    def get_users(self, email):
        active_users = get_user_model()._default_manager.filter(**{
            '%s__iexact' % 'email': email,
            'status': OK_STATUS,
        })

        return (
            u for u in active_users
            if u.has_usable_password() and
            _unicode_ci_compare(email, getattr(u, 'email'))
        )


class CustomPasswordChangeForm(PasswordChangeForm):
    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')

        if password1 and password2:
            if password1 != password2:
                raise ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )

        return password2

website/apps/ranking/views.py
from django.views.generic import View
from django.shortcuts import render

from rest_framework import filters
from rest_framework.generics import ListAPIView
from rest_framework.pagination import PageNumberPagination

from .models import Guild, Player
from .serializers import GuildSerializer, PlayerSerializer, PlayerPlayTimeSerializer
from .use_cases import get_guilds_ranking, get_players_ranking, get_nolifes_ranking


class CustomPagination(PageNumberPagination):
    page_size = 1


class PlayerRankingView(ListAPIView):
    model = Player
    queryset = Player.objects.all().order_by('-kills')
    pagination_class = CustomPagination
    serializer_class = PlayerSerializer
    permission_classes = []
    filter_backends = [filters.SearchFilter]
    search_fields = ['name']


class NolifesRankingView(ListAPIView):
    model = Player
    queryset = Player.objects.all().order_by('-playtime')
    pagination_class = CustomPagination
    serializer_class = PlayerPlayTimeSerializer
    permission_classes = []
    filter_backends = [filters.SearchFilter]
    search_fields = ['name']


class GuildRankingView(ListAPIView):
    model = Guild
    queryset = Guild.objects.all().order_by('-ladder_point')
    pagination_class = CustomPagination
    serializer_class = GuildSerializer
    permission_classes = []
    filter_backends = [filters.SearchFilter]
    search_fields = ['name']


class RankingView(View):
    template_name = 'ranking/index.html'

    def get(self, request):
        ctx = {
            'player_ranking': get_players_ranking(),
            'guild_ranking': get_guilds_ranking(),
            'nolifes_ranking': get_nolifes_ranking(),
        }

        return render(request, self.template_name, ctx)

website/apps/users/views.py
from datetime import datetime
import json

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, ListView, View

from website.apps.common.utils import compose_email
from website.apps.news.use_cases import get_all_news
from website.apps.ranking.use_cases import get_guilds_ranking, get_players_ranking

from .models import User, OK_STATUS
from .forms import CustomPasswordChangeForm, CustomPasswordResetForm, RegisterForm


class HomeView(View):
    template_name = 'home.html'

    def get(self, request):
        errors = json.loads(request.session.get('login_form_error', "{}"))

        if errors:
            del request.session['login_form_error']
            request.session.modified = True

        context = {
            'login_form': AuthenticationForm(request=request),
            'news': get_all_news(),
            'login_errors': errors,
            'player_ranking': get_players_ranking(),
            'guild_ranking': get_guilds_ranking(),
        }

        return render(request, self.template_name, context)


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    success_url = '/'
    template_name = 'users/register.html'

    def form_valid(self, form):
        self.object = User.objects.create_user(
            form.cleaned_data['login'],
            form.cleaned_data['email'],
            form.cleaned_data['social_id'],
            form.cleaned_data['password'],
        )

        message_ctx = self._prepare_message_context()

        compose_email(
            [form.cleaned_data['email']],
            subject_tpl='users/email/registration_email.txt',
            msg_tpl='users/email/registration.html',
            subject_ctx=None,
            msg_ctx=message_ctx,
        )

        return HttpResponseRedirect(self.get_success_url())

    def _prepare_message_context(self):
        return {
            'user': self.object,
            'domain': get_current_site(self.request),
            'uid': urlsafe_base64_encode(force_bytes(self.object.pk)),
            'token': default_token_generator.make_token(self.object),
        }


class CustomLoginView(LoginView):
    success_url = '/'
    form_class = AuthenticationForm
    http_method_names = ['post']
    template_name = 'home.html'

    def form_invalid(self, form):
        self.request.session['login_form_error'] = form.errors.as_json()
        return redirect('/')


class BanListView(ListView):
    model = User
    queryset = User.objects.exclude(availDt=datetime(1, 1, 1))
    template_name = 'bans/ban_list.html'
    paginate_by = 20


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.status = OK_STATUS
        user.save()

        return HttpResponse('Twój email został potwierdzony. Teraz możesz zalogować się swoim kontem.')
    else:
        return HttpResponse('Link aktywacyjny jest zły!')


class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm

    def form_invalid(self, form):
        return super().form_invalid()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs['data'] = json.loads(self.request.body)

        return kwargs


class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = CustomPasswordChangeForm

website/templates/users/login_form.html
<form class='form' method="POST" action="{% url 'login' %}">
    {% csrf_token %}

    {% for field, errors in login_errors.items %}
        {% for item in errors %}
            {% for key, error in item.items %}
                {% if key == 'message' %}
                    {{ error }}
                {% endif %}
            {% endfor %}
        {% endfor %}
    {% endfor %}

    <div class="field">
        <div class="control">
            <label for="id_username" class="label">Login</label>
            <input
                type="text"
                name="username"
                autofocus=""
                autocapitalize="none"
                autocomplete="username"
                maxlength="30"
                required=""
                value="{{ login_form.username.value|default:'' }}"
                class="input"
                id="id_username"
            />
            {{ login_form.username.errors }}
        </div>
    </div>
    <div class="field">
        <div class="control">
            <label for="id_password" class="label">Password</label>
            <input
                type="password"
                name="password"
                autocomplete="current-password"
                required=""
                class="input"
                id="id_password"
            />
        </div>
    </div>

    <input type="submit" value="Zaloguj" class="button is-primary" />
</form>

{% include 'users/password_reset.html' %}

website/templates/users/password_reset.html
<a href="#" id="password-reset">Zapomniałeś hasła?<a/>

<div class="modal" id="password-reset-modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Resetuj hasło</p>
            <button class="delete" aria-label="close"></button>
        </header>

        <section class="modal-card-body">
            <div>
                Zapomniałeś swojego hasła? Wpisz adres e-mail poniżej,
                a następnie wyślemy Ci email z instrukcją do ustawienia
                nowego hasła.
            </div>

            <div class="mt-4">
                <input
                    type="email"
                    id="id_email"
                    class="input"
                    name="email"
                    placeholder="E-mail"
                    autocomplete="email"
                />
            </div>
        </section>

        <footer class="modal-card-foot">
            <button class="button is-success send-email">Wyślij</button>
            <button class="button cancel">Zamknij</button>
        </footer>
    </div>
</div>

website/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<form class="form" method="POST">
    {% csrf_token %}

    {{ form.non_field_errors  }}

    <div class="field">
        <div class="control">
            <label for="id_login" class="label">Login</label>
            <input
                type="text"
                name="login"
                maxlength="30"
                class="input"
                required=""
                value="{{ form.login.value|default:'' }}"
                id="id_login"
            />
            {{ form.login.errors }}
        </div>
    </div>
    <div class="field">
        <div class="control">
            <label for="id_email" class="label">E-mail</label>
            <input
                type="email"
                name="email"
                maxlength="64"
                class="input"
                required=""
                value="{{ form.email.value|default:'' }}"
                id="id_email"
            />
            {{ form.email.errors }}
        </div>
    </div>
    <div class="field">
        <div class="control">
            <label for="id_password1" class="label">Hasło</label>
            <input
                type="password"
                name="password"
                maxlength="64"
                class="input"
                required=""
                id="id_password1"
            />
            {{ form.password.errors }}
        </div>
    </div>
    <div class="field">
        <div class="control">
            <label for="id_password2" class="label">Powtórz hasło</label>
            <input
                type="password"
                name="password2"
                maxlength="64"
                class="input"
                required=""
                id="id_password2"
            />
            {{ form.password2.errors }}
        </div>
    </div>
    <div class="field">
        <div class="control">
            <label for="id_social_id" class="label">Kod usunięcia postaci</label>
            <input
                type="text"
                name="social_id"
                maxlength="7"
                class="input"
                required=""
                value="{{ form.social_id.value|default:'' }}"
                id="id_social_id"
            />
            {{ form.social_id.errors }}
        </div>
    </div>

    <input type="submit" class="button is-primary" value="Zarejestruj" />
</form>
{% endblock %}